import type { Config } from 'tailwindcss/types';
const config = {
  darkMode: ['class'],
  content: [
    './(pages)/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './app/**/*.{ts,tsx}',
    './src/**/*.{ts,tsx}',
  ],
  prefix: '',
  theme: {
    container: {
      center: true,
      padding: '2rem',
      screens: {
        '2xl': '1400px',
      },
    },
    extend: {
      colors: {
        border: 'hsl(var(--border))',
        input: 'hsl(var(--input))',
        ring: 'hsl(var(--ring))',
        background: 'hsl(var(--background))',
        foreground: 'hsl(var(--foreground))',
        primary: {
          DEFAULT: 'hsl(var(--primary))',
          foreground: 'hsl(var(--primary-foreground))',
          '50': '#eff6ff',
          '100': '#dbeafe',
          '200': '#bfdbfe',
          '300': '#93c5fd',
          '400': '#60a5fa',
          '500': '#3b82f6',
          '600': '#2563eb',
          '700': '#1d4ed8',
          '800': '#1e40af',
          '900': '#1e3a8a',
          '950': '#172554',
        },
        secondary: {
          DEFAULT: 'hsl(var(--secondary))',
          foreground: 'hsl(var(--secondary-foreground))',
        },
        destructive: {
          DEFAULT: 'hsl(var(--destructive))',
          foreground: 'hsl(var(--destructive-foreground))',
        },
        muted: {
          DEFAULT: 'hsl(var(--muted))',
          foreground: 'hsl(var(--muted-foreground))',
        },
        accent: {
          DEFAULT: 'hsl(var(--accent))',
          foreground: 'hsl(var(--accent-foreground))',
        },
        popover: {
          DEFAULT: 'hsl(var(--popover))',
          foreground: 'hsl(var(--popover-foreground))',
        },
        card: {
          DEFAULT: 'hsl(var(--card))',
          foreground: 'hsl(var(--card-foreground))',
        },
        'react-primary': '#61DAFB',
        'react-accent': '#61BFAD',
        'tailwind-primary': '#38B2AC',
        'tailwind-accent': '#F6E05E',
        'astro-primary': '#FFD369',
        'astro-accent': '#47B881',
        'mysql-primary': '#00758F',
        'mysql-accent': '#F0F0F0',
        'laravel-primary': '#FF2D20',
        'laravel-accent': '#F2A30F',
        'java-primary': '#007396',
        'java-accent': '#FFA500',
        'nextjs-primary': '#000000',
        'nextjs-accent': '#FF4500',
      },
      backgroundImage: any => ({
        'gradient-react': 'linear-gradient(135deg, #61DAFB 30%, #61BFAD 60%)',
        'gradient-tailwind': 'linear-gradient(135deg, #38B2AC 30%, #F6E05E 80%)',
        'gradient-astro': 'linear-gradient(135deg, #FFD369 50%, #47B881 90%)',
        'gradient-mysql': 'linear-gradient(135deg, #00758F 30%, #F0F0F0 80%)',
        'gradient-laravel': 'linear-gradient(135deg, #FF2D20 30%, #F2A30F 100%)',
        'gradient-java': 'linear-gradient(135deg, #007396 35%, #FFA500 80%)',
        'gradient-nextjs': 'linear-gradient(135deg, #000000 15%, #FF4500 80%)',
      }),
      fontFamily: {
        body: [
          'Inter',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'system-ui',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'Arial',
          'Noto Sans',
          'sans-serif',
          'Apple Color Emoji',
          'Segoe UI Emoji',
          'Segoe UI Symbol',
          'Noto Color Emoji',
        ],
        sans: [
          'Inter',
          'ui-sans-serif',
          'system-ui',
          '-apple-system',
          'system-ui',
          'Segoe UI',
          'Roboto',
          'Helvetica Neue',
          'Arial',
          'Noto Sans',
          'sans-serif',
          'Apple Color Emoji',
          'Segoe UI Emoji',
          'Segoe UI Symbol',
          'Noto Color Emoji',
        ],
      },
      borderRadius: {
        lg: 'var(--radius)',
        md: 'calc(var(--radius) - 2px)',
        sm: 'calc(var(--radius) - 4px)',
      },
      keyframes: {
        'accordion-down': {
          from: { height: '0' },
          to: { height: 'var(--radix-accordion-content-height)' },
        },
        'accordion-up': {
          from: { height: 'var(--radix-accordion-content-height)' },
          to: { height: '0' },
        },
      },
      animation: {
        'accordion-down': 'accordion-down 0.2s ease-out',
        'accordion-up': 'accordion-up 0.2s ease-out',
      },
    },
  },
  plugins: [require('tailwindcss-animate')],
} satisfies Config;

export default config;
